controllers:
    resource: ../src/Controller/
    type: attribute
admin_dashboard:
    path: /admin
    controller: App\Controller\AdminController::dashboard

admin_book_new:
    path: /admin/books/new
    controller: App\Controller\AdminController::new

admin_book_delete:
    path: /admin/books/delete/{id}
    controller: App\Controller\AdminController::delete
    methods: POST

admin_manage_orders:
    path: /admin/orders
    controller: App\Controller\AdminController::manageOrders

admin_order_delete:
    path: /admin/orders/delete
    controller: App\Controller\AdminController::deleteOrder

homepage:
    path: /
    controller: App\Controller\DefaultController::index